### PR TITLE
Fix javadocs formatting for modern javadocs tool

### PR DESCRIPTION
**Pull request by realityforge**

### CODE REVIEW

**Comment by realityforge** [comment]
@jDramaix Any changes need to be made to this to get it accepted?

**Comment by jDramaix** [comment]
SGTM

**Comment by jDramaix** [comment]
Note: We don't close `<p>` tags. I removed `</p>` during the import

**Comment by jDramaix** [comment]
We have also decided to go with
```
<pre>{@code
// non escaped java code
}</pre>
```

Because it keep the code in the javadoc readable for human when you read the code and Intellij is able to display correctly the javadocs.

Let me know if that break some modern tools

**Comment by realityforge** [comment]
I will do. Next time I package it up I will try and verify it all still works.

Thanks

**Comment by realityforge** [comment]
Closing this as it is no longer uptodate

**Pull request closed without merging**
